// styles/login.styles.ts
import { StyleSheet, Platform } from 'react-native';

export const getLoginStyles = (theme: any) => {
  return {
    inputStyles: StyleSheet.create({
      wrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 14,
        paddingHorizontal: 16,
        height: 52,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.border,
        gap: 12,
      },
      wrapperDark: {
        backgroundColor: theme.bg,
      },
      input: {
        flex: 1,
        color: theme.textPrimary,
        fontSize: 15,
      },
    }),
    styles: StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: theme.bg,
      },
      scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 48,
      },
      logoArea: {
        alignItems: 'center',
        marginBottom: 36,
        gap: 8,
      },
      logo: {
        alignSelf: 'center',
      },
      taglineRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
      },
      tagline: {
        fontSize: 15,
        color: theme.textSecondary,
        fontWeight: '400',
        letterSpacing: 0.3,
      },
      formCard: {
        backgroundColor: theme.surface,
        borderRadius: 20,
        padding: 18,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: theme.border,
      },
      forgotButton: {
        alignSelf: 'flex-end',
        paddingVertical: 4,
        marginTop: -4,
        marginBottom: 4,
      },
      forgotText: {
        color: theme.textSecondary,
        fontSize: 13,
        fontWeight: '600',
      },
      mainButton: {
        backgroundColor: theme.primary,
        borderRadius: 16,
        height: 54,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 16,
        shadowColor: theme.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 6,
      },
      mainButtonText: {
        color: theme.bg,
        fontSize: 15,
        fontWeight: '600',
        letterSpacing: 1,
      },
      toggleButton: {
        alignItems: 'center',
        paddingVertical: 6,
      },
      toggleText: {
        color: theme.textSecondary,
        fontSize: 14,
        fontWeight: '500',
      },
      toggleTextAccent: {
        color: theme.primary,
        fontWeight: '700',
      },
      dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 24,
        gap: 12,
      },
      divider: {
        flex: 1,
        height: 1,
        backgroundColor: theme.border,
      },
      dividerText: {
        color: theme.textMuted,
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 1,
      },
      socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.surface,
        borderRadius: 16,
        height: 52,
        paddingHorizontal: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.border,
        gap: 14,
      },
      discordButton: {
        backgroundColor: '#5865F2', // Couleur fixe pour Discord
        borderColor: '#5865F2',
      },
      socialIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: theme.primary,
        alignItems: 'center',
        justifyContent: 'center',
      },
      discordIconWrap: {
        backgroundColor: 'rgba(255,255,255,0.15)',
      },
      socialButtonText: {
        color: theme.textPrimary,
        fontSize: 14,
        fontWeight: '700',
        flex: 1,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.75)',
        justifyContent: 'center',
        padding: 24,
      },
      modalContent: {
        backgroundColor: theme.surface,
        borderRadius: 22,
        padding: 24,
        borderWidth: 1,
        borderColor: theme.border,
      },
      modalHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
      },
      modalIconWrap: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: `${theme.primary}1F`,
        borderWidth: 1,
        borderColor: `${theme.primary}44`,
        alignItems: 'center',
        justifyContent: 'center',
      },
      modalCloseBtn: {
        width: 34,
        height: 34,
        borderRadius: 10,
        backgroundColor: theme.surfaceHigh || theme.border,
        alignItems: 'center',
        justifyContent: 'center',
      },
      modalTitle: {
        color: theme.textPrimary,
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 6,
        letterSpacing: 0.3,
      },
      modalText: {
        color: theme.textSecondary,
        fontSize: 13,
        lineHeight: 20,
        marginBottom: 20,
      },
      modalActions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 4,
      },
      modalBtnCancel: {
        flex: 1,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.border,
        backgroundColor: theme.surfaceHigh || theme.border,
      },
      modalBtnCancelText: {
        color: theme.textSecondary,
        fontWeight: '700',
        fontSize: 14,
      },
      modalBtnConfirm: {
        flex: 1,
        height: 48,
        backgroundColor: theme.primary,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        shadowColor: theme.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
      },
      modalBtnConfirmText: {
        color: theme.bg,
        fontWeight: '600',
        fontSize: 14,
        letterSpacing: 0.5,
      },
    }),
  };
};